version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: backDocker
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: ./frontend
      dockerfile: frontDocker
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules