version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: backDocker
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: frontDocker
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
