CREATE DATABASE IF NOT EXISTS PlacesDB;

USE PlacesDB;

CREATE TABLE IF NOT EXISTS Places (
    PlaceID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    URL VARCHAR(255) UNIQUE NOT NULL,
    Latitude DOUBLE,
    Longitude DOUBLE
);

CREATE TABLE IF NOT EXISTS Prices (
    PriceID INT AUTO_INCREMENT PRIMARY KEY,
    PlaceID INT,
    LastChecked DATE NOT NULL,
    MinimumPrice INT,
    FOREIGN KEY (PlaceID) REFERENCES Places(PlaceID)
);
